# 2020 UNIST STEM Camp : NumPy #01

## Goals 
   In this Lab session, you practice writing Python NumPy moudle 
   Most of the statistical analysis which needs data to be stored in memory uses NumPy. 
   You will be looking into the following topics in here.

Issues covered:
  1. Why NumPy and Not Python lists
  2. How to create NumPy Arrays
  3. Create N-Dimensional Array
  4. Mathematical Operations and Array Calculations 

## 1. Why NumPy and Not Python lists
   

NumPy provides efficient storage and better ways of handling data for Mathematical Operations.

NumPy is the fundamental package for scientific computing with Python. Extremely useful!!

links used:
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html    

## 2. How to create NumPy Arrays

 - import the "numpy" library as "np"

In [58]:
import numpy as np
print(np.__version__)

1.14.3


- using .array(....) function

In [59]:
np_arr = np.array([1,2,3,4,5,6])

In [60]:
np_arr  #  print(np_arr)

array([1, 2, 3, 4, 5, 6])

In [61]:
py_arr = [1,2,3,4,5,6]

In [62]:
py_arr

[1, 2, 3, 4, 5, 6]

- Check the difference between python array and numpy array

In [64]:
# insertion by string 
py_arr= [1,2,3,4,"Hello", 5,6]

In [65]:
py_arr

[1, 2, 3, 4, 'Hello', 5, 6]

In [66]:
np_arr = np.array([1,2,3,"Hello", 4,5,6])

In [67]:
np_arr

array(['1', '2', '3', 'Hello', '4', '5', '6'], dtype='<U11')

 - Create a list with values 1 to 10 and assign it to the variable "list1"
 - Create an integer array from list1 and assign it
 - Check the data type of each array (use the attribute "dtype")

In [68]:
list1= range(1, 11)
np_arr = np.array(list1, dtype = np.int32)   # np_arr = np.array(list1, "i") 
print(np_arr, np_arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10] int32


 - Create a list with values 1 to 10 and assign it to the variable "list1"
 - Create an array of floats from list1 and assign it
 - Check the data type of each array (use the attribute "dtype")

In [71]:
list1 = range(1,11)

np_arr = np.array(list1, dtype = np.float64)
print(np_arr, np_arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64


## 3. Create N-Dimensional Array

- using .array() and many other function   # create numpy array
- using .reshape() function   # reshapes the array without changing the original shape
- using .arange() function    # create sequence of numbers in array
- using .empty()              # to get a matrix of all random numbers
- using .zeros() and ones()   # numpy provides the utility to create some usual matrices which are commonly used
- using .diag()               # diagonal elements   np.diag([1,1,1,1])
- using .ravel() function 

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

In [72]:
import numpy as np
np_arr=np.arange(0,10,1)

In [73]:
np_arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
np_arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np_arr = np.empty((5,2))

In [76]:
np_arr

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [77]:
np_arr=np.empty((5,2), dtype = np.int32)

In [79]:
np_arr

array([[-152168432,        603],
       [1371076736,          0],
       [         1,          0],
       [        -1,         -1],
       [         0,          0]])

In [80]:
np_arr = np.zeros((5,2)) # Create an array of all zeros

In [81]:
np_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [82]:
np_arr = np.ones((5,2))  # Create an array of all ones

In [83]:
np_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [84]:
np_arr.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://t1.daumcdn.net/cfile/tistory/99B4C23C5A884A392C'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

In [96]:
np_arr = np.eye(3) # 3 by b matrics

In [99]:
np_arr = np.full((2,2), 7)  # Create a constant array

In [100]:
np_arr

array([[7, 7],
       [7, 7]])

1.0


#### Practice 1
- Create an array of shape (2,3,4) of zeros
- Create an array of shape (3,4,5) of ones
- Create an array with values 0 to 49 using the np.arange() 

#### Practice  2    
- Create an array of from the list [2,5,5, -7.2, 3,5, 2.7, 4.7] and assign it 
  print np_arr[1] 
- try printing np_arr[1:-4] to see what the equals?
- Create a 2-D array from the following list and assign it 
  [[2, 3.2, 5.5, -6.4, -2.2, 2.4], 
  [1, 22, 4, 0.1, 5.3, -9], 
  [3, 1, 2.1, 21, 1.1, -2]]

- try printing the following
  a[:, 3], 
  a[1:4, 0:4], 
  a[1:, 2] 

In [ ]:
import numpy as np
np_arr = np.array([2,5.5, -7.2, 3.5, 2.7, 4.7])

In [ ]:
np_arr

In [ ]:
np_arr[1]

In [ ]:
np_arr[1:4]

In [ ]:
np_arr = np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4],
                [1, 22, 4, 0.1, 5.3, -9],
                [3, 1, 2.1, 21, 1.1, -2]])

In [ ]:
np_arr

In [ ]:
np_arr[:,3]

# POPCORN QUIZ
Write a Python program to create a 2d array with 1 on the border and 0 inside.
- Sample Output


In [107]:
import numpy as np  
np_arr = np.ones((5,5))
print(np_arr)
# write your answer in here
np_arr[1:3, 1:4] = np.zeros((2,3))
print(np_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Practice 3
- Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it
- Check the shape, the size,n the maximum and minimum of the array 

- Contiunue to use the array as defined above. 
- print the array re-shaped to (2,2,2)
- print the array transposed
- print the array flattened to a single dimension

## 4. Mathematical Operations and Array Calculations 

NumPy n-dimensional arrays makes it extremely easy to perform mathematical operations on it.
- Mathematical operations with arrays
- Mathematical operations mixing scalars and arrays
- Comparison operators and Boolean operations on arrays
- Broadcasting

In [ ]:
py_arr = [1,2,3] * 2

In [ ]:
np_arr = np.array([1,2,3]) * 2 

In [ ]:
py_arr

In [ ]:
np_arr

multi dimensional mathematical operations

In [ ]:
np_arr = np.ones((5,2)) * 10

In [ ]:
np_arr

#### Practice 4
- Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the   
  variable "a" 
- Create an array from a list [2, -1, 1, 0] and assign it to the variable "b"
- Multiply array "a" by "b" and view the result. Do you understand how NumPy has used its broadcasting feature
  to do the calculation even though the arrays are different shapes?
- Multiply array "b" by 100 and assign the result to the variable "b1".
- Multiply array "b" by 100.0 and assign the result to the variable "b2".
- Print the arrays "b1" and "b2".
- Print "b1 == b2". Are they the same?
- Why do they display differently? Interrogate the typecode of each array to find out why.

In [ ]:
import numpy as np

In [ ]:
a = np.array([range(4), range(10,14)])

In [ ]:
b = np.array([2,-1,1,0])

In [ ]:
# a*b

In [ ]:
# b1

In [ ]:
#b2

In [ ]:
#print 

### Broadcasting 
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.


In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1,2])
b = np.array([5,5,5])

In [ ]:
a+b

Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example,
you can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

In [ ]:
a+5



You can think of this as an operation that stretches or duplicates the value 5 into the array [5, 5, 5], and adds the results. The advantage of NumPy's broadcasting is that this duplication of values does not actually take place, but it is a useful mental model as we think about broadcasting.

You can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:


In [ ]:
c = np.ones((3,3))

In [ ]:
c

In [ ]:
c + a



Here the one-dimensional array a is stretched, or broadcast across the second dimension in order to match the shape of j.

While these examples are relatively easy to understand, more complicated cases can involve broadcasting of both arrays. Consider the following example:


In [ ]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [ ]:
print(a)
print(b)

In [ ]:
a+b

Just as before we stretched or broadcasted one value to match the shape of the other, here we've stretched both a and b to match a common shape, and the result is a two-dimensional array! The geometry of these examples is visualized in the following figure 

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

### Rules of Broadcasting

Thanks for your attention!!! 